title: "Bhargav D Sanketi"
fontsize: 50
author: "Bhargav Sanketi"
description: "Cornell University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: true        # show article excerpts on the home page
show_frame: false        # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
  - {title: "CV", url: "/sanketi_cv.pdf", icon: clipboard-user}
  - {file: "research_projects.html", title: "Research projects", icon: project-diagram}
  - {file: "outreach.html", title: "Outreach", icon: peace}
 


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:bds245@cornell.edu"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/BSanketi"}
  - {title: Pubmed, icon: university, url: "https://pubmed.ncbi.nlm.nih.gov/?term=Sanketi%2C+Bhargav+%5BAuthor%5D&sort=pubdate"}

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
 - jekyll-feed
